# Generated by Django 4.2 on 2023-04-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_detail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_header',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_header',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_header',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('Return', 'Return'), ('Purchase', 'Purchase')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_header',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.party'),
        ),
        migrations.AlterField(
            model_name='invoice_payment',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(blank=True, choices=[('Retail Customer', 'Retail Customer'), ('Hospital', 'Hospital'), ('Corporate Customer', 'Corporate'), ('Vendor', 'Vendor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
