# Generated by Django 4.2 on 2023-04-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_productpricehistory_product_price_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_measure', to='core.product_unit_of_measure'),
        ),
    ]
