# Generated by Django 4.2 on 2023-04-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_unit_of_measure_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_unit_of_measure',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_unit_of_measure',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='product_unit_of_measure',
            name='unit_of_measure_type',
        ),
        migrations.AddField(
            model_name='product_unit_of_measure',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product_unit_of_measure'),
        ),
    ]
