# Generated by Django 4.2 on 2023-04-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_unit_of_measure_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_unit_of_measure',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
            preserve_default=False,
        ),
    ]
