# Generated by Django 4.2 on 2023-04-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_unit_of_measure_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_detail',
            name='organization',
        ),
    ]
