# Generated by Django 4.2 on 2023-04-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_invoice_detail_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_payment',
            name='organization',
        ),
    ]
